CREATE TABLE OPLATY 
(
      ID VARCHAR  NOT NULL,
      ORDER_ID VARCHAR  NOT NULL,
      DAT DATE  NOT NULL,
      SUM1 NUMERIC  NOT NULL,
      USER_ID VARCHAR ,
      COMMENTS VARCHAR ,
      ZAMER_ID VARCHAR ,
      KASSA_ID VARCHAR  NOT NULL,
    CONSTRAINT OPLATY_PK PRIMARY KEY(ID)
);
CREATE TABLE USLUGI 
(
      ID VARCHAR  NOT NULL,
      ORDER_ID VARCHAR  NOT NULL,
      NOM_ID VARCHAR  NOT NULL,
      PRICE NUMERIC  NOT NULL,
      SUMM NUMERIC  NOT NULL,
      DAT_COMPLETE DATE ,
      SOTR_ID VARCHAR  NOT NULL,
      DAT_TO_PAY DATE ,
      GROUP_ID VARCHAR  NOT NULL,
      MEASURE_ID VARCHAR  NOT NULL,
      QUANTITY NUMERIC  NOT NULL,
      ADD_WORK VARCHAR ,
      PRICE_ADD NUMERIC ,
    CONSTRAINT USLUGI_PK PRIMARY KEY(ID)
);
CREATE TABLE CONTACT 
(
      ID VARCHAR  NOT NULL,
      VERSION DATE ,
      KONTRAG_ID VARCHAR ,
      ADRESS VARCHAR ,
      PHONE VARCHAR ,
      EMAIL VARCHAR ,
    CONSTRAINT CONTACT_PK PRIMARY KEY(ID)
);
CREATE TABLE KASSA_SETTINGS 
(
      ID VARCHAR  NOT NULL,
      USER_ID VARCHAR ,
      KASSA_ID VARCHAR ,
      KASSA_NAME VARCHAR ,
    CONSTRAINT KASSA_SETTINGS_PK PRIMARY KEY(ID)
);
CREATE TABLE NOMENKLATURA 
(
      ID VARCHAR  NOT NULL,
      FULLNAME VARCHAR ,
      DELETED NUMERIC ,
      IS_GROUP NUMERIC ,
      PARENT_ID VARCHAR ,
      PARENTNAME VARCHAR ,
      USLUGA NUMERIC ,
      PREDEFINED NUMERIC ,
      VERSION DATE ,
      ARTIKUL VARCHAR ,
    CONSTRAINT NOMENKLATURA_PK PRIMARY KEY(ID)
);
CREATE TABLE ORDERS 
(
      ID VARCHAR  NOT NULL,
      DAT DATE ,
      NUM VARCHAR ,
      KONTRAG_ID VARCHAR ,
      KONTRAG_NAME VARCHAR ,
      CURR_ID VARCHAR ,
      KASSA_ID VARCHAR ,
      DIVISION_ID VARCHAR ,
      DIVISION_NAME VARCHAR ,
      USER_ID VARCHAR ,
      USER_NAME VARCHAR ,
      KURS NUMERIC ,
      KRATNOST NUMERIC ,
      DISCRIPTION VARCHAR ,
      DELETED NUMERIC ,
      VERSION DATE ,
      POSTED NUMERIC ,
      FIRM_ID VARCHAR ,
      ACTIVITIES_ID VARCHAR ,
      STATUS_ID VARCHAR ,
      STATUS_NAME VARCHAR ,
      ZAMER_ID VARCHAR ,
      ZAMER_NAME VARCHAR ,
      ZAMER_USER_NAME VARCHAR ,
      ZAMER_USER_ID VARCHAR ,
      DAT_ZAM DATE ,
      SUMM_PLAN NUMERIC ,
      DAT_COMPLETE DATE ,
      AGENT_ID VARCHAR ,
      DAT_COMPLETE_FACT DATE ,
      DIVISION_DEST VARCHAR ,
    CONSTRAINT ORDERS_PK PRIMARY KEY(ID)
);
CREATE TABLE MEASURE_UNIT 
(
      ID VARCHAR  NOT NULL,
      FULLNAME VARCHAR ,
      CODE VARCHAR ,
      DELETED NUMERIC ,
    CONSTRAINT MEASURE_UNIT_PK PRIMARY KEY(ID)
);
CREATE TABLE GROUPMEMBERS 
(
      ID VARCHAR  NOT NULL,
      G_NAME VARCHAR ,
      G_MEMBER VARCHAR ,
    CONSTRAINT GROUPMEMBERS_PK PRIMARY KEY(ID)
);
CREATE TABLE ORDER_STATUS 
(
      ID VARCHAR  NOT NULL,
      NAME VARCHAR ,
      FULLNAME VARCHAR ,
    CONSTRAINT ORDER_STATUS_PK PRIMARY KEY(ID)
);
CREATE TABLE KONTRAGENTS 
(
      ID VARCHAR  NOT NULL,
      IS_GROUP NUMERIC ,
      PARENT_ID VARCHAR ,
      FULLNAME VARCHAR ,
      DELETED NUMERIC ,
      INN VARCHAR ,
      OKPO VARCHAR ,
      KPP VARCHAR ,
      NAMEFULL VARCHAR ,
      UR_FIZ NUMERIC ,
      PREDEFINED NUMERIC ,
      IS_SUPPLIER NUMERIC ,
      IS_BUYER NUMERIC ,
      IS_MEASURER NUMERIC ,
      USER_ID VARCHAR ,
    CONSTRAINT KONTRAGENTS_PK PRIMARY KEY(ID)
);
CREATE TABLE USERS 
(
      ID VARCHAR  NOT NULL,
      FIRST_NAME VARCHAR ,
      LAST_NAME VARCHAR ,
      EMAIL VARCHAR ,
      IS_ADMIN NUMERIC ,
      LOGIN VARCHAR ,
      PREDEFINED NUMERIC ,
      U_DESCRIPTION VARCHAR ,
      IS_ZAMER NUMERIC ,
      IS_ACTIVE NUMERIC ,
      DATE_BEFORE DATE ,
      DATE_BEFIRE_ACCEPT NUMERIC ,
    CONSTRAINT USERS_PK PRIMARY KEY(ID)
);
CREATE TABLE LAST_PRICES 
(
      ID VARCHAR  NOT NULL,
      NOM_ID VARCHAR ,
      PERIOD DATE ,
      ED_IZM VARCHAR ,
      PRICE_USL NUMERIC ,
      PRICE_GOODS NUMERIC ,
    CONSTRAINT LAST_PRICES_PK PRIMARY KEY(ID)
);
CREATE TABLE NOMGROUP 
(
      ID VARCHAR  NOT NULL,
      FULLNAME VARCHAR ,
      DELETED NUMERIC ,
      IS_GROUP NUMERIC ,
      PARENT_ID VARCHAR ,
      USLUGA NUMERIC ,
      PREDEFINED NUMERIC ,
      ARTIKUL VARCHAR ,
    CONSTRAINT NOMGROUP_PK PRIMARY KEY(ID)
);
CREATE TABLE USER_SETTINGS 
(
      ID VARCHAR  NOT NULL,
      USER_ID VARCHAR ,
      DIVISION_ID VARCHAR ,
      FIRMA_ID VARCHAR ,
      CURRENCY_ID VARCHAR ,
      KASSA_ID VARCHAR ,
      MAIN_USLUGA VARCHAR ,
      ACTIVITIES_ID VARCHAR ,
      ZAMERKONTRAG_ID VARCHAR ,
      KONTRAG_ID VARCHAR ,
      NET_ID VARCHAR ,
    CONSTRAINT USER_SETTINGS_PK PRIMARY KEY(ID)
);
CREATE TABLE KASSA 
(
      ID VARCHAR  NOT NULL,
      FULLNAME VARCHAR ,
      IS_GROUP NUMERIC ,
      PARENT_ID VARCHAR ,
      CURR_ID VARCHAR ,
      DIVISION_ID VARCHAR ,
      DELETED NUMERIC ,
      PREDEFINED NUMERIC ,
      FIRMA_ID VARCHAR ,
    CONSTRAINT KASSA_PK PRIMARY KEY(ID)
);

CREATE TABLE DATA_SYNCH_ACTIONS 
(
      ID NUMERIC NOT NULL,
      SERVICE_CLASS_NAME VARCHAR NOT NULL,
      ENTITY_CLASS_NAME VARCHAR NOT NULL,
      JSON_PAYLOAD VARCHAR ,
      ACTION VARCHAR NOT NULL,
      DATE_CREATED DATE NOT NULL,
      DATE_LAST_SYNCH DATE NOT NULL,
      LAST_SYNCH_ERROR VARCHAR,
      CUSTOM_METHOD_NAME VARCHAR,
    CONSTRAINT DSA_PK PRIMARY KEY(SERVICE_CLASS_NAME ,ID)
);

CREATE TABLE WEB_SERVICE_CALL 
(
      ID NUMERIC  NOT NULL,
      CONNECTION VARCHAR ,
      REQUEST VARCHAR ,
      METHOD VARCHAR ,
      REQUEST_HEADERS VARCHAR ,
      DURATION NUMERIC ,
      REQUEST_PAYLOAD VARCHAR ,
      RESPONSE_PAYLOAD VARCHAR ,
      ERROR_MESSAGE VARCHAR ,
      TIMESTAMP DATE ,
    CONSTRAINT WEB_SERVICE_CALL_PK PRIMARY KEY(ID)
);
